import { data } from "autoprefixer";
import { url } from "inspector";

const { SitemapStream, streamToPromise } = require("sitemap");
const { Readable } = require("stream");

// An array with your links
export default async (req, res) => {
  const links = [
    { url: "/", changefreq: "daily", priority: 0.8 },
    { url: "/about/", changefreq: "daily", priority: 0.8 },
    { url: "/products/", changefreq: "daily", priority: 0.8 },
    { url: "/services/", changefreq: "daily", priority: 0.8 },
    { url: "/contact-us/", changefreq: "daily", priority: 0.8 },
    { url: "/services/rainwater-harvesting-system-for-warehouses/", changefreq: "daily", priority: 0.8 },
    { url: "/services/co-polymer-based-rainwater-harvesting-system/", changefreq: "daily", priority: 0.8 },
    { url: "/services/modular-rainwater-harvesting-system/", changefreq: "daily", priority: 0.8 },
    { url: "/services/fiber-reinforced-polymer-based-rainwater-harvesting-system/", changefreq: "daily", priority: 0.8 },
    { url: "/services/roof-top-rainwater-harvesting-system/", changefreq: "daily", priority: 0.8 },
    { url: "/services/ground-water-recharge-system-for-industries/", changefreq: "daily", priority: 0.8 },
    { url: "/services/rainwater-harvesting-vendors-in-delhi-ncr/", changefreq: "daily", priority: 0.8 },
    { url: "/services/rainwater-harvesting-vendors-in-india/", changefreq: "daily", priority: 0.8 },
    { url: "/services/box-type-rainwater-harvesting-system/", changefreq: "daily", priority: 0.8 },
    { url: "/services/storm-water-recharge-and-management-system/", changefreq: "daily", priority: 0.8 },
    { url: "/services/bioswale-for-rainwater-drain/", changefreq: "daily", priority: 0.8 },
    { url: "/services/rainwater-harvesting-system/", changefreq: "daily", priority: 0.8 },
    { url: "/services/rainwater-harvesting-system-for-industries/", changefreq: "daily", priority: 0.8 },
    { url: "/services/rainwater-harvesting-installation-company/", changefreq: "daily", priority: 0.8 },
    { url: "/services/rainwater-harvesting-system-in-india/", changefreq: "daily", priority: 0.8 },
    { url: "/services/modular-rainwater-harvesting-system-for-industries/", changefreq: "daily", priority: 0.8 },
    { url: "/services/rainwater-harvesting-system-in-delhi-ncr/", changefreq: "daily", priority: 0.8 },
    { url: "/services/rainwater-harvesting-manufacturers/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-agartala/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-agra/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-ahmedabad/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-ajmer/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-aligarh/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-allahabad/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-alwar/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-amaravati/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-amritsar/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-ayodhya/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-bangalore/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-barabanki/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-bareilly/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-batala/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-bhathinda/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-begusarai/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-belagavi/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-bhagalpur/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-bhilwara/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-bhopal/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-bhubaneswar/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-bikaner/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-chandigarh/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-chennai/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-coimbatore/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-dehradun/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-delhi/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-devanagere/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-dharamshala/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-dholpur/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-faridabad/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-gandhinagar/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-gaya/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-ghaziabad/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-gorakhpur/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-greater-noida/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-gurgaon/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-guwahati/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-gwalior/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-hyderabad/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-imphal/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-indore/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-jabalpur/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-jaipur/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-jaisalmer/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-jalandhar/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-jammu/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-jhansi/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-jodhpur/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-kakinada/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-kanpur/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-karimnagar/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-kishangarh/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-kochi/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-kolkata/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-kota/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-lucknow/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-ludhiana/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-mangaluru/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-mathura/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-meerut/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-moradabad/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-muzaffarnagar/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-nagpur/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-noida/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-pali/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-panaji/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-patiala/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-patna/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-pune/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-raipur/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-rajkot/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-ranchi/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-ratlam/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-rewa/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-shimla/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-sikar/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-solapur/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-srinagar/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-surat/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-thane/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-tirupati/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-udaipur/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-ujjain/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-vadodara/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-varanasi/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-vellore/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-visakhapatnam/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-system-in-warangal/", changefreq: "daily", priority: 0.8 },
    { url: "/blogs/", changefreq: "daily", priority: 0.8 },
    { url: "/blogs/rainwater-harvesting-for-industries", changefreq: "daily", priority: 0.8 },
    { url: "/blogs/advancing-sustainability-with-modular-rainwater-harvesting", changefreq: "daily", priority: 0.8 },
    { url: "/blogs/rainwater-harvesting-system-empower-your-life-with-sustainable-practices", changefreq: "daily", priority: 0.8 },
    { url: "/blogs/stormwater-management-in-india-a-growing-need", changefreq: "daily", priority: 0.8 },
    { url: "/blogs/a-bengaluru-architect's-blueprint-for-sustainable-living", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-agartala/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-agra/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-ahmedabad/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-ajmer/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-aligarh/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-allahabad/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-alwar/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-amaravati/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-amritsar/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-ayodhya/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-bangalore/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-barabanki/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-bareilly/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-batala/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-bhathinda/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-begusarai/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-belagavi/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-bhagalpur/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-bhilwara/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-bhopal/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-bhubaneswar/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-bikaner/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-chandigarh/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-chennai/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-coimbatore/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-dehradun/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-delhi/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-devanagere/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-dharamshala/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-dholpur/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-faridabad/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-gandhinagar/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-gaya/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-ghaziabad/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-gorakhpur/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-greater-noida/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-gurgaon/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-guwahati/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-gwalior/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-hyderabad/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-imphal/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-indore/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-jabalpur/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-jaipur/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-jaisalmer/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-jalandhar/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-jammu/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-jhansi/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-jodhpur/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-kakinada/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-kanpur/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-karimnagar/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-kishangarh/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-kochi/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-kolkata/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-kota/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-lucknow/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-ludhiana/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-mangaluru/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-mathura/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-meerut/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-moradabad/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-muzaffarnagar/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-nagpur/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-noida/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-pali/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-panaji/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-patiala/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-patna/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-pune/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-raipur/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-rajkot/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-ranchi/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-ratlam/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-rewa/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-shimla/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-sikar/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-solapur/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-sri-ganganagar/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-srinagar/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-surat/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-thane/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-tirupati/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-udaipur/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-ujjain/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-vadodara/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-varanasi/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-vellore/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-visakhapatnam/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-warangal/", changefreq: "daily", priority: 0.8 },
    { url: "/rainwater-harvesting-in-india/", changefreq: "daily", priority: 0.8 },
    { url: "/modular-rainwater-harvesting-in-india/", changefreq: "daily", priority: 0.8 },
  ];

  const stream = new SitemapStream({
    hostname: "https://www.inrainconstruction.in",
  });

  res.writeHead(200, {
    "Content-Type": "application/xml",
  });

  const xmlString = await streamToPromise(
    Readable.from(links).pipe(stream)
  ).then((data) => data.toString());

  res.end(xmlString);
};
